spring.application.name=ragnarok customers reservation system
server.port = 8080

# Thymeleaf engine configuration
# Thymeleaf engine configuration
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Configuration MariaDB
# JPA configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/ragnarok_matejmarekproject_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MatejPella!
# Update database, maybe "create" need during the development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.data.jpa.repositories.enabled=true
spring.data.jdbc.repositories.enabled=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Extra configuration for JDBC (old config for mysql)
#spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

# Date and time configuration
spring.jackson.date-format=dd.MM.yyyy
spring.jackson.time-zone=UTC


# Let enum load by the Jackson Object Mapper from JSON, in case the enum is lowercase (general rule says enum must be uppercase)
spring.jackson.mapper.accept-case-insensitive-enums=true